#!/bin/sh

url="$1"
title="$2"
descr="$3"
separator="====="

printf "%s\nT: %s\nD: %s\nC: %s\nWWW: %s\n%s\n\n" \
  "$separator" \
  "$title" \
  "`date +"%Y.%m.%d. %H:%M"`" \
  "$descr" \
  "$url" \
  "$separator" >> ~/.config/newsbeuter/bookmarks
