#!/bin/sh

# this is a simple config for herbstluftwm

. ~/.config/herbstluftwm/include.sh

hc emit_hook reload
# dunst &

hc unlock

hc pad 0 20 0 0

${HLWM_DIR}/tcsh/tags.csh
${HLWM_DIR}/tcsh/keybinds.csh
${HLWM_DIR}/tcsh/keychains.csh
${HLWM_DIR}/tcsh/theme.csh

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    $panel $monitor &
#done

${HLWM_DIR}/tcsh/rules.csh

${HLWM_DIR}/external/autorun.sh
${HLWM_DIR}/external/daemons.csh

