#!/bin/tcsh

herbstclient emit_hook reload
herbstclient unlock
herbstclient pad 0 20 0 0

${0:h}/tcsh/tags.csh
${0:h}/tcsh/keybinds.csh
${0:h}/tcsh/keychains.csh
${0:h}/tcsh/theme.csh

# mouse
herbstclient mouseunbind --all
# herbstclient mousebind $Mod-Button1 move
# herbstclient mousebind $Mod-Button2 resize
# herbstclient mousebind $Mod-Button3 zoom

herbstclient set tree_style '╾│ ├└╼─┐'

${0:h}/tcsh/rules.csh
${0:h}/external/autorun.sh
${0:h}/external/daemons.csh

