#!/bin/sh

AWT_TOOLKIT=MToolkit
#export GDK_NATIVE_WINDOWS=true
LANG=hu_HU.UTF-8
_JAVA_AWT_WM_NONREPARENTING=1

setxkbmap -model 'pc104' -layout 'hu' -variant basic
test -f ~/.Xdefaults && xrdb -load ~/.Xdefaults 
xmodmap ~/.Xmodmap

(sleep 3 ; /home/zsolt/bin/start-newsbeuter ) &

xset m 20/4
xset b off

echo Starting window manager...

/home/zsolt/bin/change-wallpaper
dbus-launch --csh-syntax  > $HOME/logfiles/dbus.csh  

tmux has-session -t main  2>/dev/null || tmux new-session -t main -d -x 149 -y 38 &
tmux has-session -t dox   2>/dev/null || tmux new-session -t dox -d -x 82 -y 40 -c /home/zsolt/docs/ &
tmux has-session -t devel 2>/dev/null || tmux new-session -t devel -d -x 167 -y 40 &

herbstluftwm > ${HOME}/logfiles/hlwm
