#!/usr/local/bin/bash

export DISPLAY=:0

LOGFILE=$1
HOOK=$2

LOGDIR=/home/zsolt/logfiles/
STLOGFILE=${LOGDIR}/hlwm-${LOGFILE}
LOGFILE=${LOGDIR}/${LOGFILE}

source ${STLOGFILE}
NEW_STATUS=`head -n 1 ${LOGFILE}` || exit 0

[ -z "${STATUS}" -o -z "${NEW_STATUS}" ] && exit 0

if [ "${STATUS}" -ne "${NEW_STATUS}" ]; then
    echo "STATUS=${NEW_STATUS}" > ${STLOGFILE}
    /usr/local/bin/herbstclient emit_hook ${HOOK} ${NEW_STATUS} 2>/dev/null || exit 0
fi


