#!/bin/sh

export DISPLAY=:0

LOGFILE=$1
HOOK=$2

LOGDIR=/home/zsolt/logfiles/
LOGFILE=${LOGDIR}/${LOGFILE}

STATUS=""

while true; do
    NEW_STATUS=`head -n 1 ${LOGFILE}`
    if [ "${STATUS}" != "${NEW_STATUS}" -a -n "${NEW_STATUS}" ]; then
        STATUS=${NEW_STATUS}
        /usr/local/bin/herbstclient emit_hook ${HOOK} ${NEW_STATUS} 2>/dev/null || exit 0
    fi
    sleep 30
done

