#!/bin/sh

DIR="${HOME}/Dokumentumok/Bethlen/matek/munkakozvez/1314/versenyek/"
FILE=`find ${DIR} -name "*nevezes*.ods" | \
    sed "s@.*/\([^/]*\)@\1@" | sort | \
    dmenu -i -l 10 -fn "Monospace-20:normal" -nb green -sb white -nf black -sf black`

if [ -n "${FILE}" ]; then
    localc `find ${DIR} -name ${FILE}`
fi

