#!/bin/tcsh

set apps = ( \
    "transmission-daemon/transmission" \
    "lowriter/LO Writer" \
    "localc/LO Calc" \
    "qmpdclient/QMpdClient" \
    "start-newsbeuter/newsbeuter" \
    "xterm/xterm" \
    "anyk/ANYK" \
    "opera -nomail/Opera" \
    "motogt/MotoGT" \
    "dosbox/DOSbox" \
    "freeciv/FreeCiv" \
    "cdcat/CdCat" \
    "openttd/OpenTTD" \
    "geogebra/GeoGebra" \
    "chrome/Chromium" \
    "wesnoth/Battle for Wesnoth" \
    "firefox/Firefox" \
)

set tmpfile=`mktemp -t hlwm-dmenu`
set ret=""
foreach app ($apps:q)
    echo ${app:t} >> ${tmpfile}
end

set answer="`sort ${tmpfile} | dmenu -i -l 15 -nb blue -sb yellow -sf black`"
rm ${tmpfile}

if ( $? == 0 ) then
    foreach app ($apps:q)
        if ( "${answer}" == "${app:t}" ) then
            ${app:h} &
            break
        endif
    end
endif

