#!/bin/sh

FIFO=~/.config/herbstluftwm/run/sxhkd.fifo

cat ${FIFO} | while read line; do
  case ${line} in
    B*)
      herbstclient emit_hook chord_enter
      ;;
    E*)
      herbstclient emit_hook chord_leave
      ;;
  esac
done
