#!/bin/sh

task_create() {
  shift
  task $* 2> /dev/null | sed -n '$ s, task.*,,p'
}

/home/zsolt/.config/herbstluftwm/scripts/herbstluftwm_hook task \
  `task_create task1 due.before:7d` \
  `task_create task2 due.before:20d and due.after:7d`
