#!/bin/sh

VPSLIST="bsd-backup bsd-builder bsd-devel bsd-uzsolt uzsolt.hu rpi"

vps=`echo ${VPSLIST} | tr ' ' '\n' | rofi -dmenu -p 'VPS > ' -l 5`
if [ $? -eq 0 ]; then
  if echo $VPSLIST | grep -q -w ${vps}; then
    myterminal vps ${vps}
  fi
fi

