#!/bin/sh

VPSLIST="backup.uzsolt.hu builder.uzsolt.hu devel.uzsolt.hu uzsolt.hu 89.185.248.126 rpi"

vps=`echo ${VPSLIST} | tr ' ' '\n' | rofi -dmenu -p 'VPS > ' -l 5`
if [ $? -eq 0 ]; then
  if echo $VPSLIST | grep -q -w ${vps}; then
    myterminal vps ${vps}
  fi
fi

