#!/bin/sh

CONFIG=~/.rsync-desktop

RSYNC_MAIN_PARAMS="-e ssh -C -avz -rRt --delete-delay"

if [ -r ${CONFIG} ]; then
  . ${CONFIG}
  [ -n "${BKPDIR}" ] && RSYNC_EXTRA_PARAMS="--backup --backup-dir=${BKPDIR}/`date +%Y-%m-%d`"
  RSYNC_PARAMS="${RSYNC_MAIN_PARAMS} ${RSYNC_EXTRA_PARAMS} ${EXCLUDE} ${DIRS} ${REMOTE}:${REMOTEDIR}"
  echo "Running rsync with ${RSYNC_PARAMS}"
  rsync ${RSYNC_MAIN_PARAMS} ${RSYNC_EXTRA_PARAMS} \
    ${EXCLUDE} \
    ${DIRS} ${REMOTE}:${REMOTEDIR}
else
  echo "No ${CONFIG}. Exit."
  exit 1
fi
