#!/bin/sh

LOGDIR=/home/zsolt/logfiles/
SERVERSVNDIR=/home/zsolt/svn/server-dotfiles

for vps in `grep "\." ~/.config/vpslist`; do
  echo " ==> ${vps}"
  (
    date
    printf "\npkg upgrade\n"
    ssh ${vps} doas /usr/local/sbin/pkg upgrade -y
    printf "\nsvn update\n"
    ssh ${vps} "/usr/bin/svnlite update ${SERVERSVNDIR}"
    printf "\nmake server-dotfiles\n"
    ssh ${vps} doas /usr/bin/make -C /home/zsolt/svn/server-dotfiles/
    printf "\n====================\n"
  ) >> ${LOGDIR}vps-${vps}.log
done
