#!/bin/sh

while read line; do
  dir=`echo ${line} | sed "s,.*/\([^/]*\),pack/\1,"`
  if [ -d ${dir} ]; then
    svn update ${dir}
  else
    svn checkout ${line}/trunk ${dir}
    ln -s . ${dir}/start
  fi
  echo
done < pack-list
